esphome:
  name: "garage"

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#  manual_ip:
#    static_ip: 
#    gateway: 
#    subnet: 255.255.255.0
  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ""
    password: ""

captive_portal:

sensor:
  - platform: dht
    pin: GPIO2
    temperature:
      id: tem
      name: "Garage Temperature"
    humidity:
      id: hum
      name: "Garage Humidity"
    update_interval: 10s

binary_sensor:
  - platform: gpio
    pin: GPIO4
    name: "Garage Sensor"
    id: pir
    device_class: motion
    on_state:
      then:
        - switch.toggle: relay_1

switch:
  - platform: gpio
    name: Motion LED
    icon: "mdi:lightbulb"
    pin: GPIO2
    id: relay_1

font:
  - file: 'Arial.ttf'
    id: font1
    size: 14

time:
  - platform: homeassistant
    id: sntp_time
    on_time_sync:
      then:
        - logger.log: "Synchronized sntp clock"

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO19

display:
  - platform: ssd1306_spi
    model: "SH1106 128x64"
    cs_pin: GPIO22
    dc_pin: GPIO23
    reset_pin: GPIO5
    contrast: 60%
    lambda: |-
      it.strftime(64, 0, id(font1),TextAlign::TOP_CENTER, "%Y-%m-%d %H:%M", id(sntp_time).now());
      it.printf(64, 16, id(font1),TextAlign::TOP_CENTER,"Temperature : %.1fc", id(tem).state);
      it.printf(64, 32, id(font1),TextAlign::TOP_CENTER,"Humidity : %.1f ", id(hum).state);
      if (id(pir).state) {
        it.print(64, 48, id(font1),TextAlign::TOP_CENTER, "Motion: Detected");
      } else {
        it.print(64, 48, id(font1),TextAlign::TOP_CENTER, "Motion: None");
      }

  
      
      
      
      
      
      