substitutions:
  name: m5
  friendly_name: m5

esphome:
  name: ${name}
  platform: ESP32
  board: m5stack-core-esp32
  on_boot:
    priority: -100.0
    then:
      - light.turn_on:
          id: recording_led
          brightness: 50%
          red: 0%
          green: 100%
          blue: 0%

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: $name "-ap"
    password: !secret wifi_password

captive_portal:

# Enable logging
logger:
  # ESP8266 only - disable serial port logging, as the HeatPump component
  # needs the sole hardware UART on the ESP8266
  baud_rate: 0
  level: DEBUG
  logs:
    component: ERROR
    
# Enable Home Assistant API
api:

web_server:

ota:
  password: !secret wifi_password

light:
  - platform: esp32_rmt_led_strip
    rgb_order: GRB
    pin: 27
    num_leds: 1
    rmt_channel: 0
    chipset: SK6812
    id: recording_led
    name: Recording Light
    effects:
      - random:
      - flicker:
      - addressable_rainbow:

binary_sensor:
  - platform: gpio
    pin:
      number: 39
      inverted: true
    name: Recording Button

switch:
  - platform: gpio
    pin: 25
    id: roland_switch
  - platform: template
    name: Roland Remote
    turn_on_action:
    - switch.turn_on: roland_switch
    - delay: 2s
    - switch.turn_off: roland_switch
